### ISSUE TITLE
Cant use markdown text objects in elements array. 

### ISSUE THREAD

**Issue by austinparkk** [raycharius/slack-block-builder#101]
**Describe the Bug**
I can't put a markdown text object as an element 
```
{
"type": "context",
"elements": [
	{
		"type": "mrkdwn",
		"text": "_5 channels maximum_"
	}
     ]
}
```

**Additional Context**
Is this not supported? I cannot find a way to do this.

**Comment by raycharius** [comment]
Hello! It does the conversion to a markdown text object under the hood, you can simply pass in strings or an array of strings. Cheers!
