### ISSUE TITLE
Builder properties should be copied

### ISSUE THREAD

**Issue by nlwillia** [raycharius/slack-block-builder#102]
**Describe the Bug**
The following code will fail with the error `Property text can only be assigned once.`

```
const commonParams = {}
Elements.Button(commonParams).text('foo')
Elements.Button(commonParams).text('foo')
```

The problem is that [Builder](https://github.com/raycharius/slack-block-builder/blob/main/src/internal/lib/builder.ts#L9) assigns the props argument to its internal properties instead of copying, so the second chained text call is trying to write to the same object.

**Expected Behavior**
This probably isn't very common and perhaps there's a practical consideration for how it's done now, but from a usage perspective the outcome is surprising and cryptic.

**Comment by raycharius** [comment]
Hi @nlwillia! Thanks for reporting this! If you'd like, feel free to send over a pull request. Otherwise, I'll get this out in the next release, which I plan to do by next Monday, with the new features added by Slack. Thanks!

**Comment by raycharius** [comment]
Thanks for the PR! I've just released this, together with some new features
