### ISSUE TITLE
Add support for new Slack elements (Number input element)

### ISSUE THREAD

**Issue by michael-pont** [raycharius/slack-block-builder#103]
**Is your feature request related to a problem? Please describe.**
Using plain text input elements for fields that are numbers requires input validation and more code to manage. It appears that Slack has a number input element: https://api.slack.com/reference/block-kit/block-elements#number which would make input in Slack UI more understandable in terms of what to enter.

**Describe the solution you'd like**
Adding Elements.NumberInput() to the current api

**Describe alternatives you've considered**
Alternatives are using existing plain text input elements

**Comment by raycharius** [comment]
Released, together with support for email input, URL input, and date time picker, in the latest version, 2.7.0
