### ISSUE TITLE
TS:  'EmailInputBuilder' is not assignable to parameter of type 'InputElementBuilder'.

### ISSUE THREAD

**Issue by ldhenry** [raycharius/slack-block-builder#106]
**Describe the Bug**
I looks like the new `EmailInputBuilder` type might not be compatible with `InputElementBuilder`.

**To Reproduce**
Create a new Modal() with the following:

``` ts
Blocks.Input()
        .label('Email')
        .dispatchAction(true)
        .element(
          Elements.EmailInput()
            .dispatchActionOnEnterPressed()
            .actionId('email_submit'),
        ),
```

This throws the following typescript error:
```
Argument of type 'EmailInputBuilder' is not assignable to parameter of type 'InputElementBuilder'.
  Type 'EmailInputBuilder' is missing the following properties from type 'TextInputBuilder': maxLength, minLength, multiline
ts(2345)
```

As a workaround I can cast the EmailInputBuilder as an InputElementBuilder:
``` ts
Blocks.Input()
        .label('Email')
        .dispatchAction(true)
        .element(
          Elements.EmailInput()
            .dispatchActionOnEnterPressed()
            .actionId('email_submit') as TextInputBuilder,
        ),
```

**Expected Behavior**
No typescript error

**Additional Context**
Thanks for everything you do!

**Comment by raycharius** [comment]
Thanks! Great catch. I missed adding the new components to type constraints. Will have an update out today!

**Comment by ldhenry** [comment]
Thanks @raycharius 🎉
