### ISSUE TITLE
Unsure how to update a modal dynamically via actions blocks

### ISSUE THREAD

**Issue by mjcbfl** [raycharius/slack-block-builder#117]
**Is your feature request related to a problem? Please describe.**
I don't think this is an issue per-se but I am unsure how to use Block Builder without this functionality

**Describe the solution you'd like**
Much of the time I want to be able to dynamically update and change modals based on input. Ie. If a user selects 'Tech Request' from a static select in an actions block, the handler sees the selection and then adds more blocks to that modal. 

My issue relates to being able to mutate existing blocks. Perhaps this exists already but I am unsure how it would work. Before using this package my go-to was to take the old body.view.blocks, mutate it as necessary, and then call client.views.update with the new blocks. 

Is there a way I can achieve this with Block Builder? Forgive me if it's built-in, I just can't figure it out!

**Describe alternatives you've considered**
I have tried getting just the blocks with .getBlocks() but the objects aren't compatible and can't be concatenated.

**Additional context**
None.

**Comment by raycharius** [comment]
Hi there, thanks for the issue! It's a tough one, especially with all of the considerations of TypeScript. To have this functionality, for this to be completely type-safe, if I'm not missing anything, you'd have to actually convert the view payload to Block Builder objects, which would be very redundant, or you would need to use something like the `as` keyword, which isn't safe. 

But I'd be interested in hearing how you imagine that as working. Something like `Modal.replaceBlockAt(index, block)`? Or maybe evening aliasing the blocks and replacing it by alias or `block_id` for that matter? 

However, I can share how I approach this. It's fit my needs in every case, but that doesn't mean it's going to necessary fit yours. 

How I approach this is that I build out the view from scratch every single time, passing in the necessary data to make decisions on adding/omitting blocks inside of the template itself. And I do that using the `setIfTruthy`, `omitIfTruthy`, etc., helpers. You can view some really simple examples of this right in [this repo](https://github.com/MacPaw/together-app/blob/main/services/ModalService.ts). Although it's not necessarily updating the views between requests, it's the same idea. 

Let me know!

**Comment by mjcbfl** [comment]
Hi Ray,

Thanks for getting back so quickly! Apologies for my slow response.

Though this differs from the way I've been using it, adjusting my approach and using these methods will satisfy my needs and probably provide a more robust way of building my app. I didn't even know they existed! I didn't notice them in the documentation. Thanks so much!

Regards,
Mike.

P.s. +1 to you for giving me the idea of putting JSON in the action_ids.
