### ISSUE TITLE
Support Markdown in text input blocks

### ISSUE THREAD

**Issue by reginapizza** [raycharius/slack-block-builder#118]
**Is your feature request related to a problem? Please describe.**
Yes, I'm trying to make a form for developers to submit help requests; their problems mostly involve a lot of code. In slack they will often mix code and plain text to describe their problems. 

**Describe the solution you'd like**
I would like a way to have a input text field that supports markdown, I don't think it's currently supported because I haven't been able to find anything about markdown for input fields and when I tried it out it didn't like `mkdwn` as a `type` value anywhere. (Sorry if I'm wrong about this, very new to block builder!)

**Describe alternatives you've considered**
I tried using markdown in slack workflows but it also doesn't have this feature I believe.

**Comment by gasparhabif** [comment]
Having a similar issue here! It would be great to have an input text fields with the exact same options that normal chat usually has.

**Comment by raycharius** [comment]
Hi there! Unfortunately, this is better directed to the folks over at Slack, as this feature is currently not supported on the platform. However, when/if they do support it, it would definitely become a part of the library

Cheers!

**Comment by reginapizza** [comment]
hey @raycharius no problem! How could I direct it towards the folks at Slack if you don't mind?

**Comment by reginapizza** [comment]
hey @raycharius can you follow up on this? I originally asked this in the [slack community forum](https://forums.slackcommunity.com/s/question/0D53a00009BR4VtCAL/i-have-a-workflow-that-has-a-form-input-that-might-require-code-when-i-format-it-in-markdown-in-the-form-it-sends-a-response-to-the-original-channel-without-the-code-formatted-but-in-the-secondary-channel-where-we-collect-responses-it-does-format-it) and was directed here so I'm not sure where to go from here...
