### ISSUE TITLE
Incomplete File block parameters

### ISSUE THREAD

**Issue by OneFlash-Jason** [raycharius/slack-block-builder#120]
**Describe the Bug**
Cannot send file as Slack Block, missing `source` parameter

**To Reproduce**
1. Upload a file using the `client.files.uploadV2` method from `@slack/web-api` WebClient instance.
2. Construct a File block using this library.
    - You can only set the blockId and externalId of the block.
3. Try to send a message using the `client.chat.postMessage` method from `@slack/web-api` WebClient instance that contains the constructed file (without the needed `source` parameter because we can't set it).

**Expected Behavior**
I should be allowed to configure the `File` block correctly, adding the required `source` and any other needed or useful parameter.

**Additional Context**
Here is the Slack api response when reproducing : 
```json
{
    "code": "slack_webapi_platform_error",
    "data": {
        "ok": false,
        "error": "invalid_blocks",
        "errors": [
            "missing required field: source [json-pointer:/blocks/0]"
        ],
        "response_metadata": {
            "messages": [
                "[ERROR] missing required field: source [json-pointer:/blocks/0]"
            ],
            "scopes": [
                "chat:write",
                "files:write"
            ],
            "acceptedScopes": [
                "chat:write"
            ]
        }
    }
}
```

**Comment by raycharius** [comment]
Thanks for the report, this has been fixed!
