### ISSUE TITLE
Plain text input is missing the optional property `multiline`

### ISSUE THREAD

**Issue by carlovsk** [raycharius/slack-block-builder#121]
**Describe the Bug**
Slack's [Plain Text Input](TextInput) supports a `multiline` option which gives the input the capability of be a larger text area rather than the usual single line input.

**To Reproduce**
1. Import the component `TextInput`
2. Try to set the option `multiline`
4. See a type error

**Expected Behavior**
This could be easily supported, as Slack already supports it. Just a matter of adding the option.

**Comment by wi-ski** [comment]
https://github.com/raycharius/slack-block-builder/pull/123

**Comment by lechu24** [comment]
Hi this feature would be helpful, because currently plain text is not allowing to add multiline property. when this will be added.
