### ISSUE TITLE
Add text() function to documentation

### ISSUE THREAD

**Issue by chriscmuir** [raycharius/slack-block-builder#20]
Via the various documentation pages for objects which support text, the text() function/setter method isn't currently documented.

For example on the getting started page it includes the following code exert:

![image](https://user-images.githubusercontent.com/10863167/90211158-8469c500-de22-11ea-85a0-e00d993ef6b7.png)

...showing a call to Blocks.Section().text('some text').

However if we look at the Section() documentation page setter methods, the text() function is missing: https://www.blockbuilder.dev/#/blocks/section

**Comment by raycharius** [comment]
Thanks! I've been swamped the last few weeks, so sorry for the late reply. I'll take a look at the doc generator to see why that method isn't showing up in the docs, but it definitely is an available method :) 

Thanks for bringing this to my attention!

**Comment by raycharius** [comment]
Updated!
