### ISSUE TITLE
Minor documentation quirk for setter methods accepting arrays

### ISSUE THREAD

**Issue by chriscmuir** [raycharius/slack-block-builder#21]
This is a minor issue in the slack-block-builder doc pages.

Where ever a object doc page has a setter method that accepts an array, the array syntax is a little amiss.  For example the Section() doc page: https://www.blockbuilder.dev/#/blocks/section

....has the following setter method:

Section.fields(string1[, ...[, stringN])

I'm guessing that should be:

Section.fields([string1, ..., stringN])

**Comment by raycharius** [comment]
Thanks! Just took at look at the way MDN documents `Array.prototype.push`, and looks like it should be:

`Section.fields([string1[, ...[, stringN]]])`

I'll make sure to get that fixed.

Just wondering, when you see this notation, is it clear to you that both of the following are valid?

`Section.fields('some string', 'some second string', 'some third string')`
`Section.fields(['some string', 'some second string', 'some third string'])`

**Comment by chriscmuir** [comment]
Thanks for the reply Ray.

To your last question, no I wasn't aware that was possible.  However my JavaScript skills aren't brilliant, so nothing surprises me ;-)

**Comment by raycharius** [comment]
Updated!
