### ISSUE TITLE
How do we use Context?

### ISSUE THREAD

**Issue by thellimist** [raycharius/slack-block-builder#23]
The [documentation](https://www.blockbuilder.dev/#/blocks/context) doesn't explain what an `Element` is. The [code comment](https://github.com/raycharius/slack-block-builder/blob/4d006fdf17ff42bb57cc60444c3132d61e858854/src/blocks/context.js#L37) says it expects `Array<string>` I assumed like the following, however, I couldn't replicate the following [block kit](https://app.slack.com/block-kit-builder/T019KHDVD1C#%7B%22blocks%22:%5B%7B%22type%22:%22context%22,%22elements%22:%5B%7B%22type%22:%22mrkdwn%22,%22text%22:%22markdown%20*element*%20exmaple%20%22%7D%5D%7D%5D%7D)

`Blocks.Context({ elements: ['my *markdown* element'] })`

Thanks

**Comment by raycharius** [comment]
Most of the methods that initialize the instance of a Block/Element/Surface typically only accept parameters that are primitive, such as the `blockId`, as [shown in the docs](https://www.blockbuilder.dev/#/blocks/context?id=params). The elements need to be passed into the builder method, such as:

`Blocks.Context({ blockId: 'someBlockId' }).elements('my *markdown* element', 'my second *markdown* element');`

Or

`Blocks.Context({ blockId: 'someBlockId' }).elements(['my *markdown* element', 'my second *markdown* element']);`
