### ISSUE TITLE
What is asBot option?

### ISSUE THREAD

**Issue by thellimist** [raycharius/slack-block-builder#33]
https://www.blockbuilder.dev/#/configuring-views

There is an option as `asBot` but it doesn't seem to be in code. 

1) If you use `user_token` can you send message as bot?
2) If you use `bot_token` can you send message as user? 

Thanks

**Comment by raycharius** [comment]
Oops! Typo, should actually be Message.asUser(), I've updated it over there in the docs 👍 

But in general, if you were to send a message with a bot token, without the `as_user` parameter set to `true`, it would actually send from Slackbot, whereas this option sends it from the app itself. Same as with a user token, it will send it as the actual user.

**Comment by thellimist** [comment]
>If you use user_token can you send message as bot?

So this is not possible?

Thanks for your fast answer

**Comment by raycharius** [comment]
As far as I know, it is not. To send a message as a user, they have to install your app directly, with the correct user scopes

**Comment by raycharius** [comment]
BTW, might want to check out Slack's community – https://slackcommunity.com

Lots of great content and answers to more Slack API-related questions!
