### ISSUE TITLE
Typescript: missing typing for Message.printPreviewUrl()

### ISSUE THREAD

**Issue by geoffp** [raycharius/slack-block-builder#35]
It seems that this is normally on `Surfaces` that inherit from `AdvancedSurface`, but `Message` has it as well.

I also had the thought that it would be nice to factor out a method that generates the preview URL, and another that prints it to `console.log()`, so consumers can do something else with the URL if they want to. I can do a separate issue for that though, if you’re game, @raycharius.

Matching PR for this issue is [over here](https://github.com/raycharius/slack-block-builder/pull/34).

**Comment by raycharius** [comment]
Thanks! I've released this. Actually made me wonder why I didn't just include this method in the `Surface` class, and just redefine in `AdvancedSurface`. Made that change in the types file to have it in only one place.

**Comment by geoffp** [comment]
Good call. I wondered that about the `AdvancedSurface`/`Surface` split.

Overall: really nice work on this, @raycharius, and I appreciate how responsive you are.
