### ISSUE TITLE
Context.elements() is typed incorrectly in types.d.ts

### ISSUE THREAD

**Issue by shyndman** [raycharius/slack-block-builder#38]
I've gathered from poking at the source code that the `Context.elements` method can also accept Markdown-formatted strings as input alongside `Element`s. Which is great, but the types.d.ts file doesn't include strings in the acceptable types.

I hacked around by declaring an overload in my own source as follows:

```typescript
declare module 'slack-block-builder' {
  namespace Block {
    export interface Context extends blockBuilder.Block.Block {
      elements(
        ...elements: Array<Element.Element | Element.Element[] | string | string[]>
      ): this;
    }
  }
}
```

I would expect to see this in the docs somewhere as well. Just a thought.

Happy to send a pull your way too.

Great library btw. Thank you. :)

**Comment by raycharius** [comment]
Thanks for noticing this! Feel free to send over a PR, will get it released ASAP

I don't have any contribution guidelines up yet, but one thing I do try to keep consistent is commit messages with emojis according to these specs (keeping the repo fun!):

https://gist.github.com/parmentf/035de27d6ed1dce0b36a

**Comment by shyndman** [comment]
👍 

Are there any other methods where strings can be accepted in place of elements?

**Comment by shyndman** [comment]
By the looks of it, `Actions.elements`, but I'm curious if it goes further. Are strings acceptable in most places you'd see an `Element` typing right now?

**Comment by raycharius** [comment]
Nope, just took a look at the docs, and looks like this is the only place. Most of the `element` or `elements` method accept only instances of an `Element` object. Same with `Actions.elements()` – only accepts `Element` objects. 

Also, it might make sense to have this accept only `string` or `Img` elements (according to Slack's docs, it's only strings or images, not any type of element)

**Comment by shyndman** [comment]
Sounds good. Give me a few.

**Comment by shyndman** [comment]
Wait wait, screwed up the emoji. Give me a sec. :)

`Actions.elements` might actually be a candidate for some tightening up, from `Element` to `ActionElement`? But I haven't investigated too deeply.

**Comment by shyndman** [comment]
Everything good? Want me to change anything?

**Comment by shyndman** [comment]
Thank you!
