### ISSUE TITLE
Add support for workflow steps

### ISSUE THREAD

**Issue by davestimpert** [raycharius/slack-block-builder#40]
Are there plans to support workflow steps? For instance when opening a configuration modal, the type needs to be `workflow_step` rather than `modal`.

**Comment by raycharius** [comment]
Added in v1.10.0 🙌 

Now there is a `WorkflowStep` top-level import. It doesn't have all of the same methods as the `Modal` object, as not all of the options are supported. It also has a `submitDisabled()` method to disable the Submit button until a user enters some input.

Enjoy!
