### ISSUE TITLE
is it possible to add plain_text and mrkdwn under elements ?

### ISSUE THREAD

**Issue by sebastiancretu** [raycharius/slack-block-builder#42]
Hi,

I am trying to add mrkdwn type under elements, but it seems this isn't possible right now. 
I am trying to achieve something like this:

```
{
	"type": "context",
	"elements": [
		{
			"type": "image",
			"image_url": "https://api.slack.com/img/blocks/bkb_template_images/notificationsWarningIcon.png",
			"alt_text": "notifications warning icon"
		},
		{
			"type": "mrkdwn",
			"text": "*No response within 5 sec*"
		}
	]
},
```

Is it currently possible? Or will it be implemented at some point ?

Thank you very much.

**Comment by rileydakota** [comment]
@sebastiancretu it doesn't appear to be sadly - I will try to submit a PR For this at some point this week assuming it is still maintained

**Comment by raycharius** [comment]
Thanks for the issue! And yes, definitely still maintained, just been busy last month or so.

Yes, this can be done. I've tried to to keep all of the magic with markdown and plain text objects under the hood, so with the `Context` block, you can pass in `Image` elements or strings, which will then be turned into markdown objects when the view is built.

Let me know if we can close this.

**Comment by rileydakota** [comment]
will give that a try and let you know

**Comment by rileydakota** [comment]
@raycharius thanks for the response - that worked for me! Might be worth adding as an example to the docs. @sebastiancretu fyi this is what I did: 
```typescript
Blocks.Context().elements(
          `:warning: markdown text here!!`,
        ),
```

**Comment by sebastiancretu** [comment]
Thank you. Yes, in this case this can be closed. It would be great to also update the docs as @rileydakota said :)
