### ISSUE TITLE
Implement .danger() function on ConfirmationDialog

### ISSUE THREAD

**Issue by bruint** [raycharius/slack-block-builder#43]
It appears the:
`Bits.ConfirmationDialog()` object does not allow you to call `.danger()` on the object, or define the style as a parameter on initialisation.

**Comment by raycharius** [comment]
Thanks for the heads up! Hadn't seen they added this, and I was one of the people to submit this feature request a while ago, so super excited this finally made it to production.

I'll get an update out within the week, with this, as well as few other things. I'm going to peruse the API docs again and see what other options have been added, and release an update with all of them.

Also, feel free to also submit a PR, but will probably release it to NPM as one larger release, and also please use [emoji commit messages](https://gist.github.com/parmentf/035de27d6ed1dce0b36a) (I really need to put up contribution guidelines and docs on tests).

**Comment by raycharius** [comment]
@bruint Hey there! Following up on this. So I sat down to add this method and realized that it [already exists](https://github.com/raycharius/slack-block-builder/blob/d6ff7f0503eb5b7b8ff57c00d266b6c2416cd4d3/src/bits/confirmation-dialog.js#L121)! 

I did, however, find an issue with type definitions where this method is not described, so it's not showing up in the IDE hints. Going to get that fixed this weekend. In the meantime, feel free to take a look at the [docs](https://www.blockbuilder.dev/#/bits/confirmation-dialog).

More soon!

**Comment by raycharius** [comment]
Fixed in v1.10.0 🙌
