### ISSUE TITLE
Templating to populate blocks dynamically. Turn JSON into a Block (reverse buildToJSON)

### ISSUE THREAD

**Issue by zaini** [raycharius/slack-block-builder#58]
**Is your feature request related to a problem? Please describe.**
Does something similar to templating exist? https://docs.microsoft.com/en-us/adaptive-cards/templating/

I want to be able to create a block and then populate it with data. What is the current best method to do so? I'm currently using json-templates but wondering if there is a more native solution.

Just being able to convert a JSON to a block (basically the reverse of buildToJSON) would be cool.

**Describe the solution you'd like**
I want to be able to create (or load/import a JSON template) a template for blocks and then be able to inject it with data, similar to Adaptive Cards: https://docs.microsoft.com/en-us/adaptive-cards/templating/

Something like this:

``` 
// const template = loadTemplate(file)
const template = Template().blocks(Blocks.Section({text: 'My name is {{user_name}}'})...)

template.expand({user_name: "Bobby"})
```

**Describe alternatives you've considered**
Currently I'm using json-templates to fill in a JSON of the block I want to populate with real data.

**Comment by raycharius** [comment]
Hi! Thanks for sending this over. I have a few questions to clarify and possibly a couple of possible solutions.

Am I correct in understanding that you are looking for a way to basically create a component that could potentially consist of a few blocks, with variables, that can have a data set passed in to render it for that certain data set? 

If so, sounds like structuring the files in a way that takes advantages of partials would be a good idea, and I can throw together a doc or example on that.

**Comment by zaini** [comment]
> Am I correct in understanding that you are looking for a way to basically create a component that could potentially consist of a few blocks, with variables, that can have a data set passed in to render it for that certain data set?

Yup. I think the MS Adaptive Cards that I linked have some good examples such as an employee card. I want to create a template but where I want to have the first name injected, I want to be able to have something like `${first_name}` or `{{first_name}` in the blocks text field and then be able to add fill in all these variables by passing in an object e.g. `{first_name: "Bob", age: 20, email: "whatever@email.com"}`

As mentioned in my OP, I'm currently doing with by using `json-template` and I could do it using `slack-block-builder` by having a function that takes in that object creates the component with the data entered and returns the JSON. (Would the latter be the suggested way of doing this sort of thing?)

I'd just like to be able to insert into the JSON instead of writing my block as a series of block functions, but I appreciate this could be done with the aforementioned method as well. (Just some of us already have JSON templates and might not want to rewrite them.)

**Comment by raycharius** [comment]
When building Block Builder, one of the things I aimed for was making it easy to break up components as atomically as necessary, by using partials. Similar to the features you'd expect from a template engine.

I'd suggest breaking up the code into files, as partials, in such a case:

``` javascript
// user-modal.js

const { Modal, Blocks } = require('slack-block-builder');
const getUserCard = require('../partials/get-user-card');

module.exports = ({ user }) => Modal()
  .title('View User')
  .blocks(
    Blocks.Section({ text: `This is the profile for ${user.name}.` }),
    ...getUserCard(user),
    Blocks.Section({ text: 'Some other blocks can be entered below.' }))
  .buildToObject();
```

``` javascript
// get-user-card.js

const { Blocks } = require('slack-block-builder');

module.exports = (user) => [
  Blocks.Section({ text: `*Name:* ${user.name}`}),
  Blocks.Section({ text: `*Email:* ${user.email}` }),
  Blocks.Section({ text: `*Slack User Name:* ${user.slackUserName}` }),
];
```

You could additionally add another layer here if necessary:

``` javascript
// get-user-card.js

const employeeCard = require('./employee-card');
const adminCard = require('./admin-card');
const defaultUserCard = require('./default-user-card');

module.exports = (user) => {
  if (user instanceof Employee) {
    return employeeCard(user);
  }

  if (user instanceof Admin) {
    return adminCard(user);
  }

  return defaultUserCard(user);
};
```

Another advantage to breaking up the UI into partials would be the ability to use them across multiple surfaces types (i.e. in a message, modal, or home tab).

Does that help?

**Comment by zaini** [comment]
Thanks. Yes that helps. My use case for having templates is probably too specific and just refactoring my existing code to be structured like this would probably be a better idea anyways.
