### ISSUE TITLE
Automatic text truncation and min/max length error handling

### ISSUE THREAD

**Issue by trevor-gullstad** [raycharius/slack-block-builder#60]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to lookup the min and max lengths for [text objects](https://api.slack.com/reference/block-kit/composition-objects#text).

**Describe the solution you'd like**
Plain Text: I'd like automatic truncation of the `text` input for `plain_text` objects based on the maximum length for the composition object field. The end of the string should be replaced with a sensible pattern like ellipses `...`. 
Ex. `"<long text>123<overflow>"` --> `"<long text>..."`.

Markdown (stretch goal): Markdown formatting aware truncation for `text` input for `mrkdwn` objects (i.e. if a bold `*` will be cut off by the truncation move it to the end before the ellipses). 
Ex. `<long text> *<bold text>*` --> `<long text> *<bold*...`

Other: Some blocks have fields which take a list of elements or composition objects. Methods to set (append) these lists should throw an error if the maximum length is exceeded. Build methods should throw an error if the minimum or maximum length is violated.

Error Handling: Whenever text is truncated a `DEBUG` message is logged. Whenever empty string is passed in for a text field, if the text field is optional discard, if required throw an error (since min length for text fields is always `1`).

**Describe alternatives you've considered**
Currently I use my own utility function to truncate text to the desired length before I pass it into the builder constructor or function. If text is not truncated properly, the slack API throws an error.

**Additional context**
[blocks](https://api.slack.com/reference/block-kit/blocks)
| object type 	| field       	| field type    	| required? 	| min_length 	| max_length 	| desired behavior 	|
|-------------	|-------------	|---------------	|-----------	|-----------:	|-----------:	|------------------	|
| *.            	| block_id    	| string        	| No        	|            	|        255 	| error               	|
| actions     	| elements    	| object[]      	| Yes       	|          1 	|          5 		| error               	|
| context     	| elements    	| (img\|text)[] 	| Yes       	|          1 	|         10 		| error               	|
| header      	| text        	| plain_text    	| Yes       	|          1 	|        150 	| truncate         	|
| image       	| image_url   	| string        	| Yes       	|          1 	|       3000 	| error               	|
|       	  	| alt_text    	| string        	| Yes       	|          1 	|       2000 	| truncate         	|
|                	| title        	| plain_text    	| No        	|          1 	|       2000 	| truncate         	|
| input       	| label       	| plain_text    	| Yes       	|          1 	|       2000 	| truncate         	|
|                 	| hint        	| plain_text    	| No        	|          1 	|       2000 	| truncate         	|
| section     	| text        	| text          	| Preferred 	|          1 	|       3000 	| truncate         |
|                	| fields      	| text          	| Maybe     	|          1 	|         10 	| error               	|
|                	| fields.text 	| string        	| Maybe     	|          1 	|       2000 	| truncate         |

[composition objects](https://api.slack.com/reference/block-kit/composition-objects)
| object type      | field         | field type     | required? | min_length | max_length | desired behavior |
|------------------|---------------|----------------|-----------|-----------:|-----------:|------------------|
| *                | action_id     | string         | Yes       |          1 |        255 | error            |
| button           | text          | plain_text     | Yes       |          1 |         75 | truncate         |
|                  | url           | string         | No        |          1 |       3000 | error            |
|                  | value         | string         | No        |          1 |       2000 | error            |
| checkboxes       | options       | option[]       | Yes       |          1 |         10 | error            |
| datepicker       | placeholder   | plain_text     | No        |          1 |        150 | truncate         |
| image            | image_url     | string         | Yes       |          1 |       3000 | error            |
|                  | alt_text      | string         | Yes       |          1 |       2000 | truncate         |
| *_select         | placeholder   | plain_text     | Yes       |          1 |        150 | truncate         |
| *static_select   | options       | option[]       | Maybe     |          1 |        100 | error            |
|                  | option_groups | option_group[] | Maybe     |          1 |        100 | error            |
| overflow         | options       | option[]       | Yes       |          2 |          5 | error            |
| plain_text_input | placeholder   | plain_text     | No        |          1 |        150 | truncate         |
| radio_options    | options       | option[]       | Yes       |          1 |         10 | error            |
| timepicker       | placeholder   | plain_text     | No        |          1 |        150 | truncate         |

[block elements](https://api.slack.com/reference/block-kit/block-elements)
| object type  	| field       	| field type 	| required? 	| min_length 	| max_length 	| desired behavior 	|
|--------------	|-------------	|------------	|-----------	|-----------:	|-----------:	|------------------	|
| confirm      	| title        	| plain_text 	| Yes       	|          1 	|        100 	| truncate         |
|                	| text        	| text        	| Yes       	|          1 	|        300 	| truncate         |
|                	| confirm     	| plain_text 	| Yes       	|          1 	|          30		| truncate         |
|                	| deny        	| plain_text 	| Yes       	|          1 	|          30		| truncate         |
| option       	| text        	| text        	| Yes       	|          1 	|          75		| truncate         |
|                	| value       	| string     	| Yes       	|          1 	|          75		| error            	|
|                	| description 	| plain_text 	| No        	|          1 	|          75		| truncate         |
|                	| url          	| string     	| No        	|          1 	|      3000 	| error            	|
| option_group 	| label       | plain_text 	| Yes       	|          1 	|          75		| truncate         |
|                	| options     	| option[]   	| Yes       	|          1 	|        100 	| error            	|

**Comment by raycharius** [comment]
Hi Trevor! Thanks for open this up. 

I'm not really sure this is in the scope of the library. Main reason being that moving validation or enforcement to the library could cause issues with changes to Slack's own API-side validation. Although any possible changes to their validation could require changes to an application, having that validation within the library would force developers to up the version of the library to take advantage of the changes, which could be an issue between major versions.

Would love to hear others thoughts!

**Comment by raycharius** [comment]
After giving this some thought, I think this is probably outside of the scope of the library – really just want to provide a readable, reusable way to build the JSON, while leaving all content at the discretion of the end user/developer.
