### ISSUE TITLE
Long list of errors after yarn add

### ISSUE THREAD

**Issue by zaini** [raycharius/slack-block-builder#63]
**Describe the Bug**
I followed the installation guide and am now getting a long list of errors. Part of it is below.

Node 10.14, TS 3.7.5

```
../../node_modules/slack-block-builder/dist/bits/attachment.d.ts:3:13 - error TS1005: '=' expected.

3 import type { BlockBuilder } from '../types';
              ~
../../node_modules/slack-block-builder/dist/bits/attachment.d.ts:3:35 - error TS1005: ';' expected.

3 import type { BlockBuilder } from '../types';
                                    ~~~~~~~~~~
../../node_modules/slack-block-builder/dist/bits/index.d.ts:5:1 - error TS1128: Declaration or statement expected.

5 export type { AttachmentBuilder, AttachmentParams, ConfirmationDialogBuilder, ConfirmationDialogParams, OptionBuilder, OptionParams, OptionGroupBuilder, OptionGroupParams, };
  ~~~~~~
../../node_modules/slack-block-builder/dist/bits/index.d.ts:5:13 - error TS1005: ';' expected.

5 export type { AttachmentBuilder, AttachmentParams, ConfirmationDialogBuilder, ConfirmationDialogParams, OptionBuilder, OptionParams, OptionGroupBuilder, OptionGroupParams, };
              ~
../../node_modules/slack-block-builder/dist/bits/index.d.ts:5:173 - error TS1109: Expression expected.
...
```

**To Reproduce**

Using Node 10.14, TS 3.7.5, yarn add slack-block-builder and import the module and run the file.

**Expected Behavior**
Not to get all those errors and for it to work.

**Additional Context**
I've tried deleting my node_modules and reinstalling. I assume this is a TS error but I'm unsure why it's only happening with this library (all the other stuff is working fine.)

**Comment by raycharius** [comment]
Thanks for reporting this. I'm going to take a look today/tomorrow

**Comment by raycharius** [comment]
Hi, I've taken a look at this. I created a Docker file with the specified versions, and installation works as expected when using `yard add`. Looking at the errors you've included – it makes me wonder if this is happening at install time (which I'm not sure in which cases errors like that would happen at install time), or when you build with TypeScript? Could you send over all of the steps you are taking in the console, step-by-step?

Seeing as the errors look like TypeScript errors spit out when trying to build the type declarations, it may be that node_modules is being included in the build, which you would want to exclude.

**Comment by zaini** [comment]
Hi, thanks for looking into this. I'm unsure on how it worked for you with TS version 3.7.5, but for me I'm not longer getting errors with version 3.8.8.

Apparently the import type used in the module was not supported. The node_modules were excluded by TS so that didn't seem to be the issue either, but idk.

Anyways I got the idea to upgrade from here: https://github.com/MichalLytek/type-graphql/issues/704

Syntax change in 3.8: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export

**Comment by raycharius** [comment]
Thanks for the info! I'm going to add some documentation to the installation guide, recommending Node 12 or higher, and requiring TypeScript 3.8 or higher.

Unfortunately, due to the way the classes are composed, there are a few places where it is not possible to not use `import type`
