### ISSUE TITLE
Trouble using with @slackapi/bolt-js client.views.open and client.views.update

### ISSUE THREAD

**Issue by M1kep** [raycharius/slack-block-builder#68]
When trying to use a Modal with the client.views.open or update methods with BoltJS, it causes an error with TypeScript. I'm not sure if this is me doing this wrong, or something else but it looks like some sort of type mismatch. The below is an example of what I'm seeing. Thanks in advance!

Versions:
Node: 16
Typescript: 4.4.3
slack-block-builder: 2.1.1
@slackapi/bolt-js: 3.6.0

```typescript
const handleShortcutTrigger: Middleware<SlackShortcutMiddlewareArgs<GlobalShortcut>> = async ({
    shortcut,
    ack,
    client,
}) => {
    await ack();
    await client.views.open({
        trigger_id: shortcut.trigger_id,
        view: genSupportRequestForm().buildToObject(),
    });
};
```

```typescript
import { Blocks, Modal, ModalBuilder } from 'slack-block-builder';

function genSupportRequestForm(): ModalBuilder {
    return Modal({
        title: 'Support Request Form',
        submit: 'Submit',
        close: 'Cancel',
        callbackId: 'support_request_form-action',
    }).blocks(
        Blocks.Section({
            text: '*Please fill out the fields below to file a Support team request:*',
        }),
    );
}

export { genSupportRequestForm };
```

Error(On the view property of the client.views.open call:

```
TS2322: Type 'Readonly<SlackViewDto>' is not assignable to type 'View'.
    Type 'Readonly<SlackViewDto>' is not assignable to type 'WorkflowStepView'.
        Types of property 'type' are incompatible.
            Type 'SurfaceType' is not assignable to type '"workflow_step"'.
```

**Comment by raycharius** [comment]
Thanks for bringing this up! When I first created the library, I was set on not having any dependencies, but it looks like it makes sense to use Slack's own definitions in V3.0.0, which will probably be sooner than later.

Interestingly, I've tried this same code in a Bolt project of mine, and it's not throwing any compilation errors. Could you also share your tsconfig?

I'm going to take a look at this in the next few days and get a fix out, but as a temporary solution, this should work:

``` typescript
import { View } from '@slack/types';

const handleShortcutTrigger: Middleware<SlackShortcutMiddlewareArgs<GlobalShortcut>> = async ({
    shortcut,
    ack,
    client,
}) => {
    await ack();
    await client.views.open({
        trigger_id: shortcut.trigger_id,
        view: genSupportRequestForm().buildToObject() as View,
    });
};
```

**Comment by M1kep** [comment]
Surprisingly, in a few other use cases the types have seemed to align pretty well which has been nice!

Below is my tsconfig:

```
{
  "compilerOptions": {
    "target": "es2020",
    "lib": ["es2020"],
    "module": "commonjs",
    "strict": true,
    "moduleResolution": "node",
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "rootDir": "src",
    "outDir": "dist"
  },
  "include": [
    "src/**/*"
  ]
}
```

If you're still unable to reproduce, I can create a small repository if needed.

**Comment by raycharius** [comment]
@M1kep I've just released a new version that addresses this issue. Can you confirm that this bug no longer reproduces on your end?

**Comment by M1kep** [comment]
@raycharius I've confirmed that fixed the issue! Thanks
