### ISSUE TITLE
Extending Blocks.Context() blockObject

### ISSUE THREAD

**Issue by Chima-ThirdBridge** [raycharius/slack-block-builder#72]
**Is your feature request related to a problem? Please describe.**
I've enjoyed working with this library and through it learning more about Slack Block Builder.  However, I've hit a wall...
It doesn't appear possible to create a context block with only plain text elements

**Describe the solution you'd like**
It would be useful to have a Context blockObject that accepts an Elements.PlainText(?params) object with text, emoji and text attributes

**Describe alternatives you've considered**

**Additional context**

Example of what I am trying to achieve here:

```
{
	"type": "context",
	"elements": [
		{
			"type": "image",
			"image_url": "https://api.slack.com/img/blocks/bkb_template_images/tripAgentLocationMarker.png",
			"alt_text": "Location Pin Icon"
		},
		{
			"type": "plain_text",
			"emoji": true,
			"text": "Location: Central Business District"
		}
	]
}
```

**Comment by raycharius** [comment]
Closing this for now, let me know if the above answer did not address your issue
