### ISSUE TITLE
Support `focus_on_load` for Block Elements

### ISSUE THREAD

**Issue by raycharius** [raycharius/slack-block-builder#76]
Slack has added a new feature to have focus on a certain block element upon opening a view, by setting `focus_on_load` on any one Block Element.

Need to add a `focusOnLoad()` method to supported Block Elements.

**Comment by vijay-prema** [comment]
I tried out this feature in a modal with two TextInputs, and I wanted to focus the second input. It didn't seem to work, first one is still focused.  v2.4.2
