### ISSUE TITLE
Unable to use TextInput as an Accessory

### ISSUE THREAD

**Issue by turnera** [raycharius/slack-block-builder#79]
If I use something like this:
```
Section({text: "Fill in data: "})
            .accessory(
                TextInput({actionId: "Example"})
            )
```
I'll get this error:
Argument of type 'TextInputBuilder' is not assignable to parameter of type 'Undefinable<SectionElementBuilder>'.
  Type 'TextInputBuilder' is missing the following properties from type 'UserSelectBuilder': confirm, initialUserts(2345)
  
  But if I do
```
  Section({ text: "button" })
         .accessory(
                    Button({
                        text: "This is the btn",
                        actionId: actionId
                    })
                )
```
Then I get no errors. Is this a bug or am I doing something wrong. An example of how to do this on the doc site would be great

**Comment by raycharius** [comment]
Hi there! Unfortunately, this is a restriction of the Slack API. It looks like this has been removed from the documentation, but you can see it reflected both in Slack's [type definitions](https://github.com/slackapi/node-slack-sdk/blob/main/packages/types/src/index.ts), as well as by trying it in [Block Kit Builder](https://app.slack.com/block-kit-builder).

**Comment by turnera** [comment]
> Hi there! Unfortunately, this is a restriction of the Slack API. It looks like this has been removed from the documentation, but you can see it reflected both in Slack's [type definitions](https://github.com/slackapi/node-slack-sdk/blob/main/packages/types/src/index.ts), as well as by trying it in [Block Kit Builder](https://app.slack.com/block-kit-builder).

Well that explains why I was getting no where!
Thanks so much for the quick-assist!
