### ISSUE TITLE
Support for rich text blocks

### ISSUE THREAD

**Issue by vonstring** [raycharius/slack-block-builder#85]
**Is your feature request related to a problem? Please describe.**
I always run into issues with formatting strings using markdown, esp if they already contain *~_`, or if I combine the various formats. Slack supports rich text blocks/sections, which allows for much better control of the formatting. But slack-block-builder does not seem to support these,.

**Describe the solution you'd like**
slack-block-builder implementation of the rich text blocks/sections as described here:
https://api.slack.com/changelog/2019-09-what-they-see-is-what-you-get-and-more-and-less
(weirdly not documented in the API docs from what I can see)

**Describe alternatives you've considered**
I build these blocks manually now, and insert them into objects created with slack-block-builder, which makes me feel sad and unclean.

**Comment by raycharius** [comment]
Thanks for sending this over! The only think that worries me about supporting these blocks is that they are not officially documented in the Slack API docs. They do show up in some of the documents as part of payloads, and also in the payloads when inspecting a message with the developer tool, but at the moment they are not publicly available. 

However, it could be interesting to create an `Experimental` object with those blocks. I'll need to think about this, and perhaps talk with someone on their end on their thoughts.

But I wonder if using the markdown helpers and Slack's markdown standard might help out here with your cases?

**Comment by raycharius** [comment]
After some thinking, probably not going to support these in the short term, until they are documented by Slack

**Comment by raycharius** [comment]
Absolutely! I plan to get this pushed out this week. Thanks!

**Comment by lemiesz** [comment]
> Absolutely! I plan to get this pushed out this week. Thanks!

Any update on this?

**Comment by nlwillia** [comment]
Note that this one also has an input counterpart https://api.slack.com/reference/block-kit/block-elements#rich_text_input

Are you interested in related contributions?  I was thinking about what a builder would look like for the `rich_text` elements.

**Comment by guyschlider** [comment]
Hi, any news about this one?

**Comment by guyschlider** [comment]
@raycharius Is this coming? should we create a PR? 
Thanks for your awesome job!

**Comment by agoodkind** [comment]
Hey there +1 also wishing for this as well.
