### ISSUE TITLE
Support building options for loading data from an External data source 

### ISSUE THREAD

**Issue by renkoh** [raycharius/slack-block-builder#86]
**Is your feature request related to a problem? Please describe.**
This library has been great to build my views, but I still need to build the options array by hand for options that are loaded async.  This results in less reusable code in my Slack App.

https://api.slack.com/reference/block-kit/block-elements#external_multi_select

**Describe the solution you'd like**
Provide a function to build the array of Option bits into an options array that can be passed to slack.

**Describe alternatives you've considered**
Alternatively, a build method on the option bit itself that can transform it in to a slack option.

Apologies if this already possible, but I couldn't find a way to do it.

**Comment by raycharius** [comment]
Thanks for bringing this up! I'm thinking this might be a case similar to the `BlockCollection` or `AttachmentCollection` functions that can be used to simply create an array of `Block` or `Attachment` objects, that would accept either an array of `OptionBuilder` or `OptionGroupBuilder` objects. 

I need to update the library today/tomorrow to include a new field for the `ButtonBuilder` object, so I'll include this in the release, too.

**Comment by renkoh** [comment]
That's awesome, it's the last bit in refactoring my Slack App, so will get onto this as soon as it's released. Thanks!

**Comment by raycharius** [comment]
Just released `OptionCollection()` and `OptionGroupCollection()` in 2.5.0! You can read more about it in the README or on the [doc site](https://www.blockbuilder.dev).

Enjoy! And thanks for this issue!

**Comment by jsryudev** [comment]
Hi, @raycharius 

Thank you for your wonderful work.
I have a question to ask you.
I am having a hard time using 'OptionCollection'.
Can I request a demo update on this?
