### ISSUE TITLE
Expand Blocks.Input params to include optional value

### ISSUE THREAD

**Issue by rexdavid** [raycharius/slack-block-builder#93]
**Describe the Bug**
My modal has optional input fields but when I tried to use : 

```
    Blocks.Input({
        label: 'some-label',
        blockId: 'some-id',
        optional: true, // this gave me error 
      })

```

**Expected Behavior**
Optional as true is supported by slack

**Additional Context**
I fixed it locally by adding optional?: boolean to /slack-block-builder/dist/blocks/input.d.ts

```
export interface InputParams {
    blockId?: string;
    hint?: string;
    label?: string;
    optional?: boolean; // this is new
}
```

reference: 
https://stackoverflow.com/questions/69553869/is-it-possible-to-make-an-input-not-required-with-slack-api
https://stackoverflow.com/questions/68950019/slack-bolt-python-how-to-make-the-input-field-in-modal-optional

**Comment by raycharius** [comment]
Hi, thanks for opening an issue. On the `InputBuilder`, you can make it optional by using the `InputBuilder.optional(bool?)` method. It's currently not a part of the constructor params.

But feel free to send over a PR if you'd like!
