### ISSUE TITLE
Typescript throws error with conditional in blocksForEach Paginator function

### ISSUE THREAD

**Issue by jam-fran** [raycharius/slack-block-builder#95]
**Describe the Bug**
Typescript throws a `Type Undefinable<ActionsBuilder>' is not assignable to type 'BlockBuilder'` error when using the `EasyPaginator` component with a conditional block inside of the `blocksForEach` function. 

**To Reproduce**
1. Create an EasyPaginator component
2. In the blocksForEach function, include at least 1 conditional block (e.g. `setIfTruthy`)

Here's an example:

```
 EasyPaginator({
  perPage: 5,
  items,
  page: 1,
  actionId: ({ offset }) => JSON.stringify(`action_id_${offset}`),
  blocksForEach: ({ item }) => [
    Divider(), 
    setIfTruthy(isCustomer,
      Section({text: 'This will make Typescript unhappy'})
      )
  ],
})
```

**Expected Behavior**
The paginated items should display as expected (they do if you ignore the TS error).

**Comment by raycharius** [comment]
Hi @jam-fran, thanks for reporting this! I can get a fix out over the weekend. If you have the time, capacity, and desire, feel free to send over a PR, too

**Comment by raycharius** [comment]
Hi @jam-fran – got this pushed out in the latest release, version 2.6.0! Thanks again!
